import mongoose from 'mongoose';

const UserSchema = new mongoose.Schema({
  fullName: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  password: { type: String, required: true },
  role: { type: String, enum: ['client', 'cleaner'], required: true },
  phoneNumber: String,
  gender: String,
  address: String,
  state: String,
  city: String,
  otherCity: String,
  profilePhoto: String,
  isAdmin: { type: Boolean, default: false },
  adminRole: String,
  subscriptionTier: { type: String, default: 'Free' },
  cleanerType: String,
  clientType: String,
  companyName: String,
  companyAddress: String,
  experience: String,
  bio: String,
  services: [String],
  chargeHourly: Number,
  chargeDaily: Number,
  chargePerContract: Number,
  chargePerContractNegotiable: Boolean,
  bankName: String,
  accountNumber: String,
  bookingHistory: { type: [String], default: [] },
  reviewsData: { type: mongoose.Schema.Types.Mixed, default: [] },
  pendingSubscription: String,
  subscriptionReceipt: mongoose.Schema.Types.Mixed,
  subscriptionEndDate: Date,
  subscriptionDate: Date,
  subscriptionAmount: Number,
  isSuspended: { type: Boolean, default: false },
  governmentId: String,
  businessRegDoc: String,
  monthlyNewClientsIds: { type: [String], default: [] },
  monthlyUsageResetDate: Date,
  createdAt: { type: Date, default: Date.now }
}, { timestamps: true });

export const User = mongoose.model('User', UserSchema);
